# Generated by Django 2.0 on 2018-02-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_ID', models.AutoField(primary_key=True, serialize=False)),
                ('patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ques', models.TextField()),
                ('ans1', models.CharField(default='', max_length=50)),
                ('ans2', models.CharField(default='', max_length=50)),
                ('ans3', models.CharField(default='', max_length=50)),
                ('ans4', models.CharField(default='', max_length=50)),
                ('correct_option', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('res_ID', models.AutoField(primary_key=True, serialize=False)),
                ('hits', models.IntegerField()),
                ('misses', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('exam_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='detailed_score',
            name='exam_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Exam'),
        ),
        migrations.AddField(
            model_name='detailed_score',
            name='ques_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='detailed_score',
            unique_together={('exam_ID', 'ques_ID')},
        ),
    ]
