# Generated by Django 2.0 on 2018-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_score',
            name='option_selected',
            field=models.CharField(default='', max_length=50),
        ),
    ]
